[package]
name = "pyre"
version = "0.1.0"
authors = ["Harrison Burt <57491488+ChillFish8@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "_pyre"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.12.1"
features = ["extension-module"]

[dependencies]
httparse = "1.3.4"
regex = "1"
once_cell = "1.4.1"
http = "0.2.1"
