[package]
name = "pyre"
version = "0.1.1"
authors = ["Harrison Burt <57491488+ChillFish8@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "pyre"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.0"
features = ["extension-module"]

[dependencies]
http = "0.2"
httparse = "1.3.4"
httpdate = "0.3"

bytes = "0.6.0"
fxhash = "0.2.1"
once_cell = "1.5.2"

crossbeam = "0.8.0"


# faster memory allocator, seems to help PyO3 a decent amount
mimalloc = { version = "*", default-features = false}

[profile.release]
lto = "fat"
codegen-units = 1



