[package]
name = "pyre"
version = "0.1.1"
authors = ["Harrison Burt <57491488+ChillFish8@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "pyre"
crate-type = ["cdylib"]

[dependencies.pyo3]
git = "https://github.com/davidhewitt/pyo3"
branch = "objects"
features = ["extension-module"]

[dependencies]
httparse = "1.3.4"
httpdate = "0.3"
bytes = "0.6.0"
once_cell = "1.5.2"
smallvec = "1.5.0"
http = "0.2"
# pythonize = "0.12.0"
# serde = "1.0"

# faster memory allocator, seems to help PyO3 a decent amount
mimalloc = { version = "*", default-features = false}

[profile.release]
lto = "fat"
codegen-units = 1



